### ISSUE TITLE
Hasher trait for XXH3_128?

### ISSUE THREAD

**Issue by JeffSpies** [koraa/xxhrs#13]
Hi, there! Great crate!

Is there a reason the Hasher trait isn't implemented for XXH3_128 but is for XXH3_64?

Thanks!

**Comment by koraa** [comment]
@JeffSpies Without looking it up, doesn't the hasher trait return u64 and XXH3_128 would require an u128 return value?

**Comment by JeffSpies** [comment]
Ah, you are correct. Thanks for following up!
